spring:
  application:
    name: markupSystem
  profiles:
    active: local
  rabbitmq:
    host: localhost
    virtual-host: vhost
    username: admin
    password: admin
    image_queue: image_queue
    video_queue: video_queue
    exchange: exchange
    image_routing_key: image.key
    video_routing_key: video.key
server:
  port: 444
  servlet:
    context-path: /markup
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
markup_system:
  scanNewVideoFixedRate: 3_600_000