spring:
  application:
    name: dataAccess
  profiles:
    active: local
  liquibase:
    change-log: classpath:main/resources/changelog/db.changelog-master.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
server:
  port: 555
  servlet:
    context-path: /data-access
